unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

# allow programs to bypass tmux
set-option -g allow-passthrough on

# do not exit tmux when killing session
set-option -g detach-on-destroy off

# start window numbers at 1 and close any gaps between window numbers
set -g base-index 1
set -g renumber-windows on

set-option -g default-shell $SHELL

# enable vi bindings for copy-mode
set-window-option -g mode-keys vi

# window splits
bind-key v split-window -h -c "#{pane_current_path}"
bind-key b split-window -c "#{pane_current_path}"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# move windows left and right with Ctrl Shift arrow key
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'xamut/tmux-network-bandwidth'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# move tmux status bar to top
set-option -g status-position top

# redraw status bar more often
set-option -g status-interval 3

# set network speed section to fixed size
set-option -g @tmux-network-bandwidth-padding 8

# tokyonight-night theme
set -g @black "#15161e"
set -g @red "#f7768e"
set -g @green "#9ece6a"
set -g @yellow "#e0af68"
set -g @blue "#7aa2f7"
set -g @magenta "#bb9af7"
set -g @cyan "#7dcfff"
set -g @white "#a9b1d6"
set -g @lightBlack "#3b4261"
set -g @lightRed "#f7768e"
set -g @lightGreen "#9ece6a"
set -g @lightYellow "#e0af68"
set -g @lightBlue "#7aa2f7"
set -g @lightMagenta "#bb9af7"
set -g @lightCyan "#7dcfff"
set -g @lightWhite "#a9b1d6"

set -g mode-style "fg=#{@blue},bg=#{@lightBlack}"

set -g message-style "fg=#{blue},bg=#{@lightBlack}"
set -g message-command-style "fg=#{@blue},bg=#{@lightBlack}"

set -g pane-border-style "fg=#{@lightBlack}"
set -g pane-active-border-style "fg=#{@blue}"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=#{@blue},bg=#{@black}"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#{@black},bg=#{@blue},bold] #S #[fg=#{@blue},bg=#{@black},nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#{@black},bg=#{@black},nobold,nounderscore,noitalics]#[fg=#{@blue},bg=#{@black}] #{prefix_highlight} #[fg=#{@lightBlack},bg=#{@black},nobold,nounderscore,noitalics]#[fg=#{@blue},bg=#{@lightBlack}] #(ipconfig getsummary en0 | grep ' SSID' | awk '{print $3}') #[fg=#{@blue},bg=#{@lightBlack}] #{network_bandwidth}  #{battery_percentage}  %Y-%m-%d  %H:%M #[fg=#{@blue},bg=#{@lightBlack},nobold,nounderscore,noitalics]#[fg=#{@black},bg=#{@blue},bold] #(hostname) "

setw -g window-status-activity-style "underscore,fg=#{@white},bg=#{@black}"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#{@white},bg=#{@black}"
setw -g window-status-format "#[fg=#{@black},bg=#{@black},nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=#{@black},bg=#{@black},nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#{@black},bg=#{@lightBlack},nobold,nounderscore,noitalics]#[fg=#{@blue},bg=#{@lightBlack},bold] #I  #W #F #[fg=#{@lightBlack},bg=#{@black},nobold,nounderscore,noitalics]"

# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "#[fg=#{@yellow}]#[bg=#{@black}]#[fg=#{@black}]#[bg=#{@yellow}]"
set -g @prefix_highlight_output_suffix ""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
